### ISSUE TITLE
Support sending code chunks in R script delimited by `#%%` 

### ISSUE THREAD

**Issue by apoorvalal** [Ikuyadeu/vscode-R#517] opened 2021-01-04 23:36 UTC
**Describe the solution you'd like**
I'm really liking the package so far; thanks for the great work on it. I'm trying to migrate from the Hydrogen package for Atom because of the application instability of Atom, and miss the ability to create and run code cells delimited by `#%%`, which helps a lot in interactive development. It also doesn't alter command line runs using `Rscript` at all.

**Additional context**
Sendcode on sublime implemented it recently as well - see https://github.com/randy3k/SendCode#block-expansion

**Comment by renkun-ken** [comment] 2021-01-05 01:15
Duplicate of #191.

With rmarkdown chunk support implemented, I think this code chunk in R script should be straightforward.

**Closed by renkun-ken** 2021-01-05 01:15 UTC
Labels: feature-request
