### ISSUE TITLE
run source code button is not displayed.

### ISSUE THREAD

**Issue by fdq09eca** [Ikuyadeu/vscode-R#685] opened 2021-06-27 20:45 UTC
![image](https://user-images.githubusercontent.com/51902242/123558921-e14b4100-d790-11eb-9ad3-c9872becf358.png)
as shown above, the Run source code button is blacked..

**Comment by eitsupi** [comment] 2021-06-28 04:59
@fdq09eca I think it's a duplicate of #635
You may need to update your VS Code or the extensions.

**Closed** 2021-06-28 09:23 UTC
Labels: bug
