### ISSUE TITLE
Environment and Dataframe Preview

### ISSUE THREAD

**Issue by ChristopheRoyer21** [Ikuyadeu/vscode-R#257] opened 2020-03-14 15:23 UTC
**Describe the bug**
Preview Environment and Preview Dataframe both don't work. The problem is not the same that I got some months ago.  Session watcher is on

**To Reproduce**
1. Open or create a R script
2. Create a simple data.frame
3. Try to use the command R: Preview Dataframe
4. Create some other variables
5. Try to use the command R: Preview Environment
6. See error

**Do you want to fix by self? (I hope your help!)**

No, sorry

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/34045208/76684930-3720c780-65e6-11ea-9a4b-937ea010c0f4.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - VSCode Version: 1.43.0
 - R Version: 3.6.1
 - vscode-R version: 1.2.7

**Comment by AmineI** [comment] 2020-03-21 00:48
I am unable to reproduce the issue on my end, although I have the same environment info you provided. 
Could you post more info ? An example code maybe, and when this issue started

And please try on another path (for example, your desktop), or with VS Code run with administrator rights, to eliminate eventual folder permission issues

**Comment by ChristopheRoyer21** [comment] 2020-03-21 02:11
![Capture](https://user-images.githubusercontent.com/34045208/77217206-0fa29100-6af7-11ea-8023-3f059b4b3a3b.PNG)
Here is an example. You can see that it cannot find the `.csv`. Run as Administrator and a new simple project on my desktop. (Sorry for comments in french, that's how my VS Code seems to be set.

I tried again today and for the command `Preview dataframe, three thing happen:
1. It works normally (it was the first time for me
2. It asks me to install the Excel Viewer extension (even though I already have it"
3. There is a message in the console saying that it cannot find the file `.csv`.

This screenshot is what happen with `Preview Environment`. This command has never worked, I don't even know what it does exactly (how it preview the environment)

**Comment by renkun-ken** [comment] 2020-03-21 02:35
Are you trying to use the original Preview Environment and data frame not based on session watcher, or use the data viewer provided by session watcher?

Currently, the old command `Preview Environment` and `Preview Data Frame` are not switched to use data viewer based on session watcher, we'll probably do it at some point if session watcher is enabled.

Since your session watcher is on, then you could preview your environment by running  the following commands in your R session:

* `View(globalenv())` to preview global environment
* `View(some_data)` to preview `some_data` object using data viewer

**Comment by ChristopheRoyer21** [comment] 2020-03-21 02:44
I think you're right. View(some_data) has always worked. I always used it even when I was using RStudio. However I never thought of trying View(globalenv()). And at least that is working.

So if I understand well, the commands `Preview Data Frame` and `Preview Environment` are commands that are used without session watcher. Since I'm using it, I should simply used the `View`function in R. I guess that explains why they weren't working in my case. Thank you

**Comment by renkun-ken** [comment] 2020-03-21 03:50
Actually, `View()` in enhanced by session watcher to support viewing almost any object, e.g. vector, data.frame, list, environment, function, linear regression model/summary, etc.

**Comment by magic-lantern** [comment] 2020-06-03 23:20
I've noticed a similar problem where environment and dataframe preview do not work, but I don't have the "R: Session Watcher" enabled. I primarily see the problem when my environment grows

As an example, I connect to my remote Linux server first, then create a simple R file with this:

```r
print('hello world')
a <- c(1, 2, 3, 4, 5)
```

and then invoke the `Preview Environment` feature. It works. However, if I then add to my script like so:

```r
print('hello world')
a <- c(1, 2, 3, 4, 5)
b <- c('a', 'b', 'c')
```

and run everything in the same R session, then attempt to launch the `Preview Environment` it only shows variable `a` exists. Here's my R session output:

```r
R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> print('hello world')
[1] "hello world"
> a <- c(1, 2, 3, 4, 5)
> write.csv(data.frame(name=ls(),class=sapply(ls(), function(x) {class(get(x, envir = parent.env(environment())))[1]}),out=sapply(ls(), function(x) {capture.output(str(get(x, envir = parent.env(environment()))), silent = T)[1]})), '/home/me/project/.tmp/environment.csv', row.names=FALSE, quote = TRUE)
> print('hello world')
[1] "hello world"
> a <- c(1, 2, 3, 4, 5)
> b <- c('a', 'b', 'c')
> write.csv(data.frame(name=ls(),class=sapply(ls(), function(x) {class(get(x, envir = parent.env(environment())))[1]}),out=sapply(ls(), function(x) {capture.output(str(get(x, envir = parent.env(environment()))), silent = T)[1]})), '/home/me/project/.tmp/environment.csv', row.names=FALSE, quote = TRUE)
```


Also, I've noticed that as my environment grows (load lots of libraries and custom objects) at some point I start getting this error instead:

```r
> write.csv(data.frame(name=ls(),class=sapply(ls(), function(x) {class(get(x, envir = parent.env(environment())))[1]}),out=sapply(ls(), function(x) {capture.output(str(get(x, envir = parent.env(environment()))), silent = T)[1]})), '/home/me/project/.tmp/environment.csv', row.names=FALSE, quote = TRUE)
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file '/home/me/project/.tmp/environment.csv': No such file or directory
```

I'm guessing the `No such file or directory` error is due to something in my environment, but the not seeing the current environment seems like it might be a bug in this extension.

**Comment by andycraig** [comment] 2020-08-14 01:53
@magic-lantern Thank you very much for this info. I was able to produce this error by declaring new variables and running `R: Preview Environment` after each one. Eventually I get the 'No such file or directory'. If I keep trying it, it works again. Sometimes I experience the problem you noted where recently declared variables are not included.

There is quite a lot of async temporary file management code in https://github.com/Ikuyadeu/vscode-R/blob/master/src/preview.ts and I guess the source of the problems lie somewhere in there. I wonder if we could remove most of that code by using a JavaScript library for temporary file management.

**Comment by andycraig** [comment] 2020-08-14 02:12
Here are a few options:

1. Debug and fix the existing code.
1. Use one of the `fs.mkdtemp` family of functions to create a separate temporary directory for each preview file. This would have the disadvantage of using more space (temporarily), but would hopefully fix these bugs.
1. Remove the session watcher's experimental status (that is, activate it for all users). Change viewing data frames and the environment be done via the session watcher instead of via the current `R: Preview Environment` and `R: Preview Dataframe` commands.

@renkun-ken What do you think about option 3?

**Comment by renkun-ken** [comment] 2020-08-14 02:23
I guess we could redirect `R: Preview Environment` to sending `View(globalenv())` and `R: Preview Dataframe` to sending `View(x)` if session watcher is enabled?

**Comment by andycraig** [comment] 2020-08-14 02:30
That would be fine too, but it would still leave buggy versions of those commands for anyone who hasn't enabled session watcher. If session watcher is ready to be enabled for all users, then we don't need to fix those commands at all. But you're definitely the best person to judge if session watcher is ready to be enabled for all users 😃 

If it's too early to enable session watcher for all users, my preference would be option 2.

**Comment by renkun-ken** [comment] 2020-08-14 07:14
It looks okay for me to enable session watcher by default and allow user to opt out, but I'd rather wait for https://github.com/microsoft/vscode/issues/102449 to be fixed which I think is an important use case (show browser tab under remote).

**Comment by andycraig** [comment] 2020-08-15 03:20
Let’s wait for that issue to be fixed then 👍

**Comment by andycraig** [comment] 2020-08-16 00:59
I might have a try at fixing these `R: Preview Environment` and `R: Preview Dataframe` bugs at some point but I don't use these commands so it's pretty low on my priority list. If anyone wants to have a try at this, that would be great!

**Comment by cecilialee** [comment] 2021-02-06 01:29
I'm following the above suggestions to use the `View()` command in viewing R objects. I wonder are there any ways to change the color theme to dark?

<img width="1232" alt="Screenshot 2021-02-06 at 9 27 32 AM" src="https://user-images.githubusercontent.com/8072787/107104707-c4ec4d80-685d-11eb-80ef-e5e3297e4f0d.png">

**Comment by renkun-ken** [comment] 2021-02-06 03:42
@cecilialee We'll add dark theme support with https://github.com/Ikuyadeu/vscode-R/issues/506 being resolved.

**Comment by renkun-ken** [comment] 2021-06-27 07:27
Closing as fixed.

**Closed by renkun-ken** 2021-06-27 07:27 UTC
Labels: bug, help wanted
