### ISSUE TITLE
 Failed to connect (okButton) outlet from (SelectList) to (NSButton): missing setter or instance variable

### ISSUE THREAD

**Issue by Darklanx** [Ikuyadeu/vscode-R#88] opened 2018-09-17 03:06 UTC
- Mac OS
Can't work while trying to run my script.
I did open the script containing my R script.

One thing worth notice is that after pressing Command+Shift+S, my R will open up automatically
 
2018-09-17 11:06:16.346 R[53054:4524720] Failed to connect (cancelButton) outlet from (SelectList) to (NSButton): missing setter or instance variable
2018-09-17 11:06:16.346 R[53054:4524720] Failed to connect (okButton) outlet from (SelectList) to (NSButton): missing setter or instance variable

<img width="1102" alt="2018-09-17 10 54 50" src="https://user-images.githubusercontent.com/26689157/45604555-1ebf0380-ba68-11e8-9676-bb54f0cf8e1c.png">

**Comment by Darklanx** [comment] 2018-09-22 09:47
I thought that the issue shows because I didn't open the folder in vscode that contains the R script, just mentioning it that I open it but the error is still there.

**Comment by andycraig** [comment] 2019-10-30 22:38
Hi @Darklanx, there have been a number of updates to vscode-R, so could you check whether the problem is still occurring?

Please do the following:

1. Create a folder `temp-r`containing a file `temp.R`, which contains only the text

```
iris
```

2. Check that the vscode-R version is 1.1.7
3. Disable all extensions except vscode-R and vscode-r-lsp
4. Use 'Open Folder...' and select `temp-r`
5. Open `temp.R`
6. Place the cursor on 'iris'
7. Use command `R: Run Selection/Line`

Thank you!

**Comment by andycraig** [comment] 2019-12-01 04:20
I am hoping this issue no longer occurs and I am going to close it, but if anyone is still experiencing it after following the steps above, please post!

**Closed by andycraig** 2019-12-01 04:20 UTC
Labels: needs information
