### ISSUE TITLE
Cannot read property 'isActive' of undefined

### ISSUE THREAD

**Issue by ohmlovesampere** [Ikuyadeu/vscode-R#96] opened 2019-01-31 02:29 UTC
**Describe the bug**
I want to see the data frame when I use R in VS Code, but 'R: Preview Dataframe' didn't work, it tells "Cannot read property 'isActive' of undefined".
How to deal with the problem? Or is there another way to show the data frame?
Forgive my poor English.

// R.exe path for windows
"r.rterm.windows": "C:\\Program Files\\R\\R-3.5.2\\bin\\x64\\R.exe",

**Environment (please complete the following information):**
 - Windows 10
 - VSCode Version 1.30.2
 - R Version 3.5.2

**Additional context**

**Comment by ohmlovesampere** [comment] 2019-01-31 09:55
> I think this might be caused by the Excel Viewer extension by GrapeCity not being found or not loading correctly. Can you check that it is installed, and, if it is, try reloading it?

Thanks for you help, you are right. I didn't download that extension, now it doesn't show the false again. But it tells "This does not appear to be a dataframe.", I start to learn R in VS Code yesterday, i wanna know how can I see the data frame.

**Comment by ohmlovesampere** [comment] 2019-01-31 10:10
> I think this might be caused by the Excel Viewer extension by GrapeCity not being found or not loading correctly. Can you check that it is installed, and, if it is, try reloading it?

And I have another question. You know, we I write R command with VS Code, it will help me check if there are any mistakes. If there is a mistake, it will show a green wave line. I want to cancel this green wave line. How can I do? You know, it makes me crazy, for it always tell me "Variable and function names should be all lowercase." or "lines should not be more than 80 characters."

**Comment by andycraig** [comment] 2019-01-31 11:54
It sounds like the original issue of 'Cannot read property 'isActive' of undefined' has been resolved, which is good to hear.  If so, could you close this issue?

I've reproduced the 'This does not appear to be a dataframe' issue, which I believe is a bug.  Could you create a new issue for this?  I don't think it is currently possible to view dataframes using the `R: Preview Dataframe` command. 

The green line problem sounds like you want to turn off a linter.  There are several open issues relating to the R linter `lintr`.  Could you check whether any of them describe your issue?  (I think #60 might be related.) If not, you could create a new issue for this too.

**Comment by andycraig** [comment] 2019-02-02 23:16
The 'This does not appear to be a dataframe' problem is #67.

**Comment by andycraig** [comment] 2019-04-20 05:04
I asked for this issue to be closed prematurely - sorry @ohmlovesampere! When the Excel Viewer extension by GrapeCity is not installed, the error message should indeed state that clearly.

The problem is almost certainly in the `checkcsv()` function in `preview.ts`. The `extensions.getExtension()` definition probably changed at some point and caused this function to stop working properly.

**Closed** 2019-04-27 10:42 UTC
Labels: bug, good first issue

**Comment by tbkw** [comment] 2020-08-10 16:21
I have just completed the install as directed. I'm running vscode on Mojave 10.14.6 and have installed the grapecity.gc-excelviewer extension. However, I cannot view a dataframe. I am trying to view the "cars" dataframe but get an error in the bottom right saying that "This does not appear to be a dataframe". Any help would be appreciated, thanks!
