### ISSUE TITLE
Run function examples (`#'`) as code 

### ISSUE THREAD

**Issue by pat-s** [Ikuyadeu/vscode-R#384] opened 2020-07-18 21:02 UTC
Code starting with `#'` (e.g. function examples) cannot be run line-by-line.
Instead, the function is sourced (i.e. the commented code is skipped) when hitting `mac+enter` while the cursor is in one of the `#'` lines.

Would be great if this could be supported.

**Comment by renkun-ken** [comment] 2020-07-19 02:37
Duplicate of #147. Closing this now.

**Closed by renkun-ken** 2020-07-19 02:37 UTC
Labels: feature-request
