### ISSUE TITLE
IntelliSense should suggest dataframe variables after dplyr pipe (%>%)

### ISSUE THREAD

**Issue by danielbasso** [Ikuyadeu/vscode-R#527] opened 2021-01-18 23:56 UTC
In my quest to replace Rstudio, I found this extension. After some troubled start (even opened a "bug request that was totally my fault), I'm linking it a lot. I can preview dataframes, have a session explorer and even show plots and help in separated tabs.

There is only one feature that I'm missing a lot and makes a huge difference in my workflow. `dplyr` has become a standard for data munging with R. It's clean, is part of tidyverse, has a standardized  syntax, etc, etc. When using Rstudio, whenever you start with a dataframe and then use the pipe (`%>%`) operator, all the dataframes variables became available as suggestions for autocompletion:

![image](https://user-images.githubusercontent.com/20959177/104971306-26db3500-59cd-11eb-875c-f0abb498be03.png)

Even works after the first pipe:

![image](https://user-images.githubusercontent.com/20959177/104971404-7588cf00-59cd-11eb-8f74-bdca3cd8b76c.png)

This is a huge time saver for me, because I normally work with dataframes that have 100+ variables whose variable names consists of abbreviations of words, theoretical example "loa_tot_prc" (loan total price).

Unfortunately, the same doesn't happen with the current state of Vscode, at least from what I searched:

![image](https://user-images.githubusercontent.com/20959177/104971629-18d9e400-59ce-11eb-82b9-3a3903b3e472.png)

(here I created the `my_df` object outside the script file otherwise IntelliSense will suggest variable names just because it found them earlier in the code).

My workaround now is to call an `names(my_df)` and then manually search the variable names that exists.

Because the logic behind this is "kinda" straightforward:

1. Check for pipe operator;
2. Call `names()` for the dataframe prior to the pipe;
3. Use the result of the `names()` call as suggestions.

I could try and implement it by myself, but I have -10 experience developing extensions to Vscode, or with Vscode in general. I was reading about how this could be done (https://code.visualstudio.com/api/language-extensions/programmatic-language-features) and it seems doable, at least in theory. 

What do you guys think? It's hard, not so much? Maybe if pointed to the right direction I could try by myself. I need help/instructions in this regard.

**Comment by psobolewskiPhD** [comment] 2021-01-19 18:20
Hmm, for me this works already?
<img width="640" alt="image" src="https://user-images.githubusercontent.com/76622105/105076111-f35ee000-5a8a-11eb-931c-151dabc94349.png">
To be fair, var1, var2, var3 were at the bottom of the list, so I had to hit up-arrow.

Interestingly, when I repeated your example *exactly*, in other words having the df defined in the terminal and not the script window, it does't work anymore...

**Comment by danielbasso** [comment] 2021-01-19 23:45
Hi @psobolewskiPhD, 

thank you for your reply.

IntelliSense sometimes suggest variable names simply because they are present elsewhere in the script file. If you, load a dataset from a file or from a database, it won't work that way. Check my previous post:
 
> (here I created the my_df object outside the script file otherwise IntelliSense will suggest variable names just because it found them earlier in the code).

I'm willing to give this implementation a try, but I would need some help, specially in the beginning.

**Comment by renkun-ken** [comment] 2021-01-20 01:36
Duplicate of #323.

Closing this in favor of the existing one.

**Closed by renkun-ken** 2021-01-20 01:36 UTC
Labels: feature-request
