### ISSUE TITLE
Tilde character not passed to terminal

### ISSUE THREAD

**Issue by arcalb** [Ikuyadeu/vscode-R#145] opened 2019-11-17 18:55 UTC
- VSCode Version: 1.40.1
- VSCode-R Version: 1.1.8
- OS Version: Windows 10

using function lm I noticed that the tilde character, "~", is not passed to the terminal. Note that I have configured the italian keyboard

**Comment by andycraig** [comment] 2019-11-17 23:33
Hi @arcalb, thanks for using vscode-R! Could you provide a short example that says:

1. The code you are sending to the terminal
1. The command you are using to send the code
1. The text that appears in the terminal

Also, have you enabled the setting `r.bracketedPaste`?

Thank you!

**Comment by arcalb** [comment] 2019-11-18 09:36
1) I try to send to the terminal the code

lm(1:3 ~ 1:3)

2) I select the row and I send the code with ctrl+enter

3) and the text that appears in the terminal is

> lm(1:3  1:3)
Errore: unexpected numeric constant in "lm(1:3  1"

and yes I tried in the both cases with disabled and enabled the option
r.bracketedPaste

Il giorno lun 18 nov 2019 alle ore 00:33 Andrew Craig <
notifications@github.com> ha scritto:

**Comment by andycraig** [comment] 2019-11-18 22:50
Great, thank you for providing that information. Let’s try to figure out where the problem is occurring. Could you try the following and let me know the results?

1. Instead of sending the code with Ctrl-Enter, send the code using the command `Terminal: Run Selected Text in Active Terminal`

2. Create a non-R terminal (the default Windows terminal), and send the code using `Terminal: Run Selected Text in Active Terminal`

Thank you!

**Comment by andycraig** [comment] 2019-11-18 22:54
Please note I edited to add `rem` in front of the code, as I think `lm` is a Windows command.

**Comment by arcalb** [comment] 2019-11-19 09:25
1) the tilde symbol is passed to the internal terminal (without executing R)
2) even if I created the external terminal through the command "open new external terminal" the command "Run Selected Text in Active Terminal" created an internal terminal and run the code in it

**Comment by andycraig** [comment] 2019-11-19 11:22
Thank you for trying those and letting me know the results.

To summarise:
- Sending code to the R console with Ctrl-Enter does NOT send the tilde
- Sending code to the R console with `Terminal: Run Selected Text in Active Terminal` DOES send the tilde

If I've got that wrong, please let me know.

If that's correct, it sounds like it might be a bug somewhere in the vscode-R code that chooses and sends the code. I'll have a look and see if I can see where it might be happening.

**Comment by arcalb** [comment] 2019-11-19 12:58
I've also tried a copy and paste in the terminal. It works outside R, it
doesn't work if I run R in the terminal. Therefore I think it can be also
due to the keys and text coding in Rterm.exe executed in the vscode
terminal. Consider that, for instance, also the arrows key don't work
inside R but work in the terminal outside R.

Il mar 19 nov 2019, 12:22 Andrew Craig <notifications@github.com> ha
scritto:

**Comment by andycraig** [comment] 2019-11-19 13:21
Thanks for the update! I’ll be pleased if it’s not a vscode-R bug.

As a workaround, perhaps try the radian console instead of the standard R console?
https://github.com/randy3k/radian
It’s an alternative R console that feels much more modern and generally has more keyboard support. It might handle pasting the tilde properly.

If you have any more updates let us know!

**Comment by arcalb** [comment] 2019-11-19 16:10
I've installed radian, throug python 3.7.5 (because with the version 3.8.0,
pip returned an error). Now the arrows-key work but again the tilde symbol
is not passed. Therefore it is not the R console.

Il giorno mar 19 nov 2019 alle ore 14:21 Andrew Craig <
notifications@github.com> ha scritto:

**Comment by andycraig** [comment] 2019-11-19 22:50
Thanks for trying radian, sorry to hear it didn’t help either.

> I've also tried a copy and paste in the terminal. It works outside R, it
> doesn't work if I run R in the terminal.

To confirm: 
- When you paste a tilde into a non-R terminal in VSCode, it works
- When you paste a tilde into an R terminal in VSCode, it doesn’t work

Can you try these?
1. Paste a tilde into an R terminal NOT in VSCode
1. Paste a tilde into a Python terminal in VSCode

**Comment by arcalb** [comment] 2019-11-20 10:17
1. it doesn't work, both in cmd and powershell
2. it works both in cmd and powershell

Il giorno mar 19 nov 2019 alle ore 23:50 Andrew Craig <
notifications@github.com> ha scritto:

**Comment by andycraig** [comment] 2019-11-20 23:34
Thank you for trying all these variations!

If pasting an tilde into an R terminal outside of VSCode doesn’t work, then it sounds like this might be an R problem rather than a vscode-R problem.

The only vscode-R approach I can think of is to modify the `runTextInTerm` function so that it detects tilde characters and replaces them with something like [this](https://stackoverflow.com/a/31015232). I’m not sure if that would work though! Also, I wouldn’t be able to test this so you would probably have to make this change yourself. If you do want to try this, I am happy to provide assistance where I can.

**Comment by andycraig** [comment] 2019-12-01 04:15
@arcalb I think we've identified this as an R problem rather than a vscode-R problem, so I'm going to close this issue. But if you disagree please post, and we can continue looking into it.

**Closed by andycraig** 2019-12-01 04:15 UTC

**Comment by andycraig** [comment] 2020-05-05 02:41
From https://github.com/Ikuyadeu/vscode-R/issues/307#issuecomment-623518415

> PS: previously I noticed another issue in Windows with the Italian keyboard (#145) that it was due to Rterm.exe, therefore, I reported it to the R developers (https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17679) now solved in R version 4.0.0.

**Comment by albertoarcagni** [comment] 2022-05-27 07:57
Hello,

I open again this issue because the solution to it maybe crated a new issue. Now the problem is exactly the opposite: I write lm(y ~ x) the command in the console is lm(y ~~ x).

I tried to copy and paste in the windows terminal the problem is the same, I tried in the PowerShell it works fine. The problem there is only if I'm running R. I tried with python the copy and paste works fine.

**Comment by eitsupi** [comment] 2022-05-27 10:49
Have you updated to R 4.2.0?
R 4.2.0 now uses utf-8 on Windows, so that may be the cause.

**Comment by albertoarcagni** [comment] 2022-05-28 13:50
I've tried but nothing changed.

Il ven 27 mag 2022, 12:49 eitsupi ***@***.***> ha scritto:

**Comment by aropele** [comment] 2022-08-20 02:52
The same issue exists here; when running the `r.runSelection` command, VSCode is unable to pass "~" while using the Italian keyboard.

Possibly the Italian keyboard's incomplete raw mapping is to blame for this:
![immagine](https://user-images.githubusercontent.com/30937097/185726086-01eeae66-bea8-45af-85a2-053d024546c5.png)


As we can see, the JSON does not contain the tilde character:
![immagine](https://user-images.githubusercontent.com/30937097/185726154-aa4cfb0d-f435-4fb5-9908-c16f73819eed.png)

Beyond the tilde, the issue impacts all special characters that on a foreign keyboard can only be entered via a key combination that makes use of the numeric keypad. 

Is it possible to modify the local raw key mapping?

**Comment by albertoarcagni** [comment] 2022-09-02 08:10
Hello everyone,

after this bug report I understood that is not a problem of the vscode extension but an R problem. So I notified the bug to Bugzilla and I is solved in the development version. Note that in the bug report there is also the referment to the original bug:
https://bugs.r-project.org/show_bug.cgi?id=18391

Best,
Alberto

**Comment by andycraig** [comment] 2022-09-02 10:36
@albertoarcagni That's great to hear! Thank you for investigating and reporting the bug on Bugzilla, and for letting us know the positive outcome!
