### ISSUE TITLE
Cannot support Chinese in the Interactive Window?

### ISSUE THREAD

**Issue by Thinking2018** [Ikuyadeu/vscode-R#152] opened 2019-12-12 02:40 UTC
I use R3.6.1
When I excute R code in VScode by using R extension, the Chinese characters are just ignored and they disappear.

<img width="693" alt="微信截图_20191212103932" src="https://user-images.githubusercontent.com/42349201/70678006-bfcc5680-1ccb-11ea-8cb8-4a452c3b0c59.png">

**Comment by renkun-ken** [comment] 2019-12-12 02:48
I tried sending code with Chinese characters to both `radian` and `R` under Ubuntu, everything looks normal here.

![image](https://user-images.githubusercontent.com/4662568/70678395-ed65cf80-1ccc-11ea-80dc-1673bc730a5e.png)

I guess it is a Windows-specific issue?

**Comment by Thinking2018** [comment] 2019-12-12 02:54
May be it is an issuse for Windows, I use Windows 10. 
Are there any suggestions for that problem ?
I have tried to change my file encoding into utf-8 and gbk, but neither works

**Comment by andycraig** [comment] 2019-12-13 11:24
@Thinking2018 I’ve duplicated this on Windows 10. I’ve tried pasting Chinese characters in Rterm started outside of VSCode and that doesn’t work either.

As a workaround, I suggest [radian](https://github.com/randy3k/radian). I was able to send Chinese characters to that on Windows 10 with no problems. (It’s also much nicer to use than the normal R console!)

**Comment by randy3k** [comment] 2019-12-20 11:37
RTerm.exe doesn't support unicode chars at all, there is no way to type and display non-ascii chars. On the other hand, `radian` supports unicode chars (with a catch): it only works perfectly if your computer locale is the **same** as that of the text.

If your computer doesn't have a matching locale (for example, your computer locale is English but the text is in Chinese), then radian might fail to display the text. You are still able to paste the text, just not able to display it probably.

<img width="474" alt="Screen Shot 2019-12-20 at 3 26 34 AM" src="https://user-images.githubusercontent.com/1690993/71251971-8e114c00-22d8-11ea-904f-722aa11653e7.png">

(PS: if you are using a relatively old version of `radian`, the text may be displayed correctly, but it was based on a hack that breaks a lot of other things so I have reverted it in recent versions.)

Ultimately, the issue is caused by upstream R because R doesn't print unicode chars directly unless RGui is used. I have filed an issue https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17677
and radian will be updated if we hear anything from R maintainers.

**Comment by randy3k** [comment] 2019-12-20 11:44
Forgot the mention that the above only applies to Windows. `radian` fully supports unicode chars in Linux and macOS.

**Comment by andycraig** [comment] 2019-12-23 09:47
@randy3k Thank you for that info! Hopefully Rterm will be updated to support Unicode at some point.

I’m going to close this as it’s an R problem rather than a vscode-R problem, and there’s a good workaround (radian).

**Closed by andycraig** 2019-12-23 09:47 UTC

**Comment by diandian11** [comment] 2019-12-29 10:15
你好，同样遇到vscode里输入中文的问题，有没有好的解决方案呢？谢谢

**Comment by Thinking2018** [comment] 2019-12-29 10:50
您好，


谜之bug，目前无解。可用radian替代，但它不是R。


谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"diandian11"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月29日(星期天) 晚上6:15
收件人:&nbsp;"Ikuyadeu/vscode-R"<vscode-R@noreply.github.com&gt;;
抄送:&nbsp;"彩虹后的阳光"<761134060@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Ikuyadeu/vscode-R] Cannot support Chinese in the Interactive Window? (#152)




你好，同样遇到vscode里输入中文的问题，有没有好的解决方案呢？谢谢

**Comment by diandian11** [comment] 2019-12-29 12:13
radian不能成功部署。
![image](https://user-images.githubusercontent.com/31070013/71556788-9eaf8800-2a77-11ea-973f-425cc4da24a7.png)

**Comment by diandian11** [comment] 2019-12-29 12:20
vscode 能不能直接使用Rgui呢
