### ISSUE TITLE
Implement shared R workspace in VS Live Share

### ISSUE THREAD

**Issue by gvelasq** [Ikuyadeu/vscode-R#555] opened 2021-02-16 17:50 UTC
**Is your feature request related to a problem? Please describe.**
Following our recent [post](https://ivelasq.rbind.io/blog/vscode-live-share/) and @ivelasq's [tweet](https://twitter.com/ivelasq3/status/1357136366568689664) trialing VS Code and VS Live Share for remote pair programming in R, one of the features we hoped could be implemented in `vscode-R` is a shared R workspace across host and guest(s) sessions in [VS Live Share](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare).

**Describe the solution you'd like**
Implementation of a shared R workspace while using VS Live Share. Per the [issue](https://github.com/MicrosoftDocs/live-share/issues/4098) I filed in the VS Live Share repository, this could be implemented using the [VS Live Share Extension API](https://www.npmjs.com/package/vsls).

**Describe alternatives you've considered**
Currently the host and guest(s) have separate R workspaces. This is useful behavior when host and guest(s) are inspecting the codebase and objects separately. However, sometimes to debug a problem it is useful for users to inspect the object(s) in one another's R workspace directly.

**Additional context**
I initially filed an issue [here](https://github.com/MicrosoftDocs/live-share/issues/4098) and was directed to this repository as a shared R workspace is considered custom extension behavior.

**Comment by ElianHugh** [comment] 2021-02-24 09:36
I've only skimmed the live share API, but this might be possible using the URI conversion exposed by it. At the moment, the workspace viewer relies on a globalenv.json file to populate its contents,  so this should theoretically be doable if we expose the file to the guest session. 

As I haven't used live share, I'm not sure if there would be read/write issues, but presumably there is a method of resolving this if that were the case.

If no one is eager to fiddle with this, I can have a further look!

**Comment by ElianHugh** [comment] 2021-02-26 11:42
Some progress!

![image](https://user-images.githubusercontent.com/60372411/109295989-8e37a080-7827-11eb-97e8-6151edc1b03f.png)

**Comment by ElianHugh** [comment] 2021-03-03 10:16
Unfortunately, I think this is going to need a little more work. It seems that whilst uri conversion works, the files themselves are not actually exposed to the guest session. I'll update when I have more progress :)

**Comment by gvelasq** [comment] 2021-03-03 18:12
@ElianHugh, thank you very much for your efforts. TypeScript is outside of my expertise but I did have a few questions:

1. Is there an alternative to sharing the data itself (e.g., the global environment plus all loaded package functions)? Similar to how in VS Live Share currently the host can optionally allow the generic terminal to be set to read/write so that the guest can execute arbitrary code on the host machine, would it be possible for the R terminal to be set to read/write and thus allow the guest to use host compute resources, writing to a single shared R workspace for both guest and host? If so, perhaps the data itself would not need to be passed but instead messages back and forth from guest to host.
2. As far as sharing data itself, there would be potential issues in directly sharing the data, e.g. the guest session may not have R installed (esp. if connecting from a browser which will be supported [soon](https://twitter.com/FilishaShah/status/1357908285156773890)), or may have R installed but not the correct version (in which case packages may not work), or a different OS such that the global environment binaries may not be compatible, nor the loaded packages. It seems that for this use case perhaps a separate feature exposing a [shared R server](https://docs.microsoft.com/en-us/visualstudio/liveshare/use/vscode#share-a-server) might be helpful?

Perhaps related to the data issue:
https://github.com/MicrosoftDocs/live-share/issues/1895
https://github.com/MicrosoftDocs/live-share/issues/3791
https://github.com/MicrosoftDocs/live-share/issues/4010

Many thanks again for your efforts and for considering.

**Comment by ElianHugh** [comment] 2021-03-04 02:43
> 
> 
> @ElianHugh, thank you very much for your efforts. TypeScript is outside of my expertise but I did have a few questions:
> 
>  Is there an alternative to sharing the data itself (e.g., the global environment plus all loaded package functions)? 
Not at all, thank you for your input! I've had a little sleep on this and I think sharing the data may not technically be required.  Whilst the session viewer (and by extension workspace viewer) require data to communicate between vscode and R, I don't think they actually need to be synced across sessions. This is because the globalenv.json that is used to populate the workspace viewer is populated from the R session's globalenv.

So, what we really need is to A) sync the filepaths appropriately, so that it points to a guest or host's /tmp/ folder, instead of trying to expose the host's directly, and B) sync the session PIDs. This should be able to be achieved through a combination of RPC messages, and assessing whether the LiveSession user is a host or guest (or other).

> Similar to how in VS Live Share currently the host can optionally allow the generic terminal to be set to read/write so that the guest can execute arbitrary code on the host machine, would it be possible for the R terminal to be set to read/write and thus allow the guest to use host compute resources, writing to a single shared R workspace for both guest and host? If so, perhaps the data itself would not need to be passed but instead messages back and forth from guest to host.

Off the top of my head, I don't think this is possible directly, but through messaging it could work like you've outlined. The issue would be that session.ts (vscode-r session viewer) would have to be heavily modified for guest sessions, which isn't ideal.

> As far as sharing data itself, there would be potential issues in directly sharing the data, e.g. the guest session may not have R installed (esp. if connecting from a browser which will be supported soon), or may have R installed but not the correct version (in which case packages may not work), or a different OS such that the global environment binaries may not be compatible, nor the loaded packages. It seems that for this use case perhaps a separate feature exposing a shared R server might be helpful?

I think that if data sharing is incompatible with a given guest session, this may be a separate issue, as vscode-r makes heavy use of files for communication between the IDE and R. Although, the data method outlined above *should* generally work for LiveShare sessions. I think the most likely issues would crop up with browser sessions, and how they potentially handle filesystems.

**Comment by ElianHugh** [comment] 2021-03-09 12:40
So, good news, the live share implementation seems to be working **across computers**! At present, the workspace viewer is functioning, with just a few things to iron out!

![DIlr19Dumx](https://user-images.githubusercontent.com/60372411/110471598-37a64e00-80d4-11eb-8652-e3fa8ac54ec4.gif)

The implementation is no doubt going to need a little more work and polish for release, but the rough skeleton is working :) We also have to wait for api access as mentioned above, but hopefully that gets sorted!

**Comment by renkun-ken** [comment] 2021-03-10 00:11
Just notice the badge of [C/C++](https://github.com/Microsoft/vscode-cpptools) extension

<img width="625" alt="image" src="https://user-images.githubusercontent.com/4662568/110555714-0a12e080-8178-11eb-8b42-ef2325de6e9d.png">

I guess we could just follow how it handles dependency on Live Share api?

**Comment by ElianHugh** [comment] 2021-03-18 03:02
The request update is now working for guest sessions. This means that:
- View() works
- Help viewer works
- Browser works
- Webview works

A potential annoyance is that calling view() opens for *all* users in the session. In the future when we have background sessions this might be easier to deal with.  I'm not 100% sure how it would work yet, but I was thinking a potential solution could be to have a user-id associated with calls, and only passing vscode commands to a matching vscode session.

**Comment by ElianHugh** [comment] 2021-03-23 13:54
View() works based on UUID now :)

![O3fs9eMCof](https://user-images.githubusercontent.com/60372411/112157228-ef605300-8bde-11eb-8164-49ed3e7b522d.gif)

**Comment by ElianHugh** [comment] 2021-03-28 13:10
Hey all! I've been looking at implementing some settings relating to liveshare, and thought I'd get some input into what might be neat to have!

At the moment I'm trying with:
> Attach on join
     Whether the host should call .vsc.attach() every time a guest joins
> Minimum guest permissions
    The minimum access level required for guests to send commands to the host terminal (think view, rm)
> Always allow attach
    Whether guests can call .vsc.attach() without having the requisite minimum permission

**Comment by gvelasq** [comment] 2021-03-30 16:23
@ElianHugh, thanks very much for your hard work on feature. I see that there's an issue in Live Share that needs to be resolved first, but regarding the option:

> * Attach on join
> Whether the host should call .vsc.attach() every time a guest joins

Would it be possible to implement a custom tab similar to Live Share's `Share Terminal...` shown [here](https://docs.microsoft.com/en-us/visualstudio/liveshare/use/vscode#share-a-terminal), which would allow the host to `Share R Terminal...` and then choose the access level for the guest?

**Comment by ElianHugh** [comment] 2021-03-31 23:42
Hey, and thanks for the kind words! Re: a custom tab, would you be able to clarify what you mean please? Technically, changing the access level for both the terminal and the workspace already exists (although like we've discussed isn't updated after joining a session). 

I could probably create some kind of quick access to the settings, like a button to enable/disable attach on join?

**Comment by gvelasq** [comment] 2021-04-01 21:29
@ElianHugh thanks, and sorry if I misunderstood since I haven't had a chance to try your PR yet. By 'custom tab' I was using the terminology from the Live Share documentation [here](https://docs.microsoft.com/en-us/visualstudio/liveshare/use/vscode#share-a-terminal), though I see now that 'custom tab' refers to the tab opened by clicking an extension's icon in the sidebar, and the `Share Terminal...` 'entry' within the Live Share custom tab is what I meant to refer to.

I was suggesting that that somewhere either in the Live Share custom tab, or in the R extension custom tab, there be entries to optionally share either the R terminal or R workspace or both: `Share R Terminal...` and `Share R Workspace...`. The default behavior would remain not sharing either the R terminal or R workspace, but these entries would allow one to do so without having to alter global settings. In the case of the Live Share custom tab, these new entries could go directly below the `Share Terminal...` entry in the screenshot below. In the case of the R extension custom tab, the entries could go somewhere in the Workspace menu.

https://docs.microsoft.com/en-us/visualstudio/liveshare/media/vscode-share-terminal-viewlet.png

These entries may be useful to have a graphical interface by which to share additional terminals (e.g., a host may have multiple R and non-R terminals open and want to share only one of the R terminals) and to avoid having the host type `.vsc.attach()` manually to attach the guest R terminal/workspace — or were you suggesting calling `.vsc.attach()` as a global setting? I think if the R terminal/workspace sharing workflow mimics what is implemented in Live Share, it would overall introduce less surprises for R extension users.

Many thanks for considering!

**Comment by ElianHugh** [comment] 2021-04-05 01:18
Right, sorry, that makes sense! 

I think we might have had a bit of a misunderstanding re: `.vsc.attach()` - at the time of writing, this was called automatically on the host's active (and attached) R terminal. I've now modified this, so an R call isn't required for guests.

I've been working on a small menu for toggling R LiveShare settings, as I agree with you that having them as global settings is cumbersome. The settings can be toggled by right clicking and selecting toggle, just like choosing whether terminals are read/write or read only.

![image](https://user-images.githubusercontent.com/60372411/113527121-0a9e6b80-95ac-11eb-8179-cc6c6d4208aa.png)
- So, to answer your idea about not wanting to attach by default, guests are *only* attached to the workspace when workspace sharing is enabled

I went for this menu as opposed to a context menu, as I think ideally we don't want to crowd other extensions with custom behaviours, and there is more than one setting that can be tweaked by the host (which could be hard to find & cumbersome if in a context menu).

I'd love to hear your feedback on the menu, and thank you again for your input!

**Comment by gvelasq** [comment] 2021-04-09 17:22
Thanks very much @ElianHugh again for your hard work on this — the proposed menu looks great to me.

I also agree with what you mentioned, re: not crowding other extensions with custom behavior.

**Comment by BerriJ** [comment] 2021-04-15 13:14
Will this enable guests to see help pages also when they do not have R installed at all? Or do they have to have R installed locally?

I want to use VSC Live-Share to present code to my students but as I can see only the R-Scripts and the Console is shared, when I type ?mean, for example, nothing happens on the remote machine.

**Comment by ElianHugh** [comment] 2021-04-16 01:15
> 
> 
> Will this enable guests to see help pages also when they do not have R installed at all? Or do they have to have R installed locally?
> 

Hi @BerriJ, the intent of the feature is to have the guests rely on the host's R client for all R processes. Ideally, all the guest would need is the vscode-R extension installed. 

... Having said that, your comment made me double check how a guest without R functions in a LiveShare setting. I've confirmed that guests have access to plots, browsers, the workspace viewer, and data viewer. _However_, the help viewer doesn't seem to be working for guests at the moment - thanks for bringing that to my attention!

**Closed** 2021-06-11 16:21 UTC
Labels: feature-request
