### ISSUE TITLE
Preview Environment error in file

### ISSUE THREAD

**Issue by c-yin** [Ikuyadeu/vscode-R#92] opened 2018-10-10 21:44 UTC
![image](https://user-images.githubusercontent.com/8154646/34399399-208b9392-ebc2-11e7-8ffe-1fd65ecb476f.png)
@Ladvien are these error related to?

_Originally posted by @Victsz in https://github.com/Ikuyadeu/vscode-R/issues/22#issuecomment-354221889_

I'm coming up with this problem as well. how can I preview the dataframe?

**Comment by andycraig** [comment] 2019-09-25 10:26
I am encountering this problem when using `R: Preview Environment`, which I believe is the command that was used in the above screenshot. `R: Preview Dataframe` works fine.

Steps to reproduce:

1. Create a new file 'temp.R' containing just the text 'iris'

2. Run command `R: Create R Terminal`

3. Run command `R: Preview Environment`

`R: Preview Dataframe` DOES work. Also, if the file is completely empty, `R: Preview Environment` works.

Windows 10 Home, Version 10.0.18362 Build 18362
VSCode 1.38.1
vscode-R 1.1.3

**Comment by andycraig** [comment] 2019-09-25 10:43
Works fine in Linux:

Ubuntu 18.04.2 LTS
VSCode 1.37.1
vscode-R 1.1.3

It looks like the screenshot above is also Windows, so I'm guessing it's a Windows issue.

**Comment by simonmcbrown** [comment] 2019-12-06 17:21
Can confirm R: Preview Environment has same issue in RHEL7.  Oddly when I first invoked this command it complained saying it needed an extension, would I like to install.  I clicked yes, it seemed to install something and then the error below.  Subsequent calls does not complain of a missing extension, but looking at my installed extensions nothing new has appeared.  I cant remember what it wanted to install unfortunately.

> write.csv(data.frame(name=ls(),class=sapply(ls(), function(x) {class(get(x, envir = parent.env(environment())))[1]}),out=sapply(ls(), function(x) {capture.output(str(get(Error in file(file, ifelse(append, "a", "w")) :  T)[1]})), '/home/h03/hadsx/extremes/ukcp/18ukcp/code/pp/tasmax/.tmp/environment.csv', row.names=FALSE, quote = TRUE)
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file '/home/h03/hadsx/extremes/ukcp/18ukcp/code/pp/tasmax/.tmp/environment.csv': No such file or directory

vscode-R 1.1.8
VSCode: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:30.162Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 3.10.0-1062.4.3.el7.x86_64

**Comment by andycraig** [comment] 2019-12-07 00:16
@simonmcbrown Thank you for reporting this. I had thought it was just a Windows issue but evidently it can happen on Linux too.

The extension it prompts you to install is https://marketplace.visualstudio.com/items?itemName=GrapeCity.gc-excelviewer That is odd that it’s not showing up as installed though.

**Comment by simonmcbrown** [comment] 2019-12-09 12:09
hmm.  Well OK, now it is there, gc-excelviewer that is.  The preview environment bug has not changed.

**Comment by izk8** [comment] 2019-12-15 15:33
Same issue as @simonmcbrown on linux, ubuntu 18.04.

**Comment by andycraig** [comment] 2020-02-05 13:04
While experimenting with the `Preview` command problems I also found that even after installing the gc-excelviewer the message about it not being installed kept appearing. The message went away after restarting VSCode, but this seems like a bug.

**Comment by tbkw** [comment] 2020-08-10 16:51
I'm having the same issue

Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:08:29.692Z (2 wks ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0


can't open the iris dataframe after following all installation instructions

**Comment by andycraig** [comment] 2020-08-14 01:23
> can't Preview the cars dataframe after following all installation instructions. I get the following message "This does not appear to be a dataframe."

Created issue #389 for this.

> In addition R: Preview Environment results in the following error:
> 
> Command 'R: Preview Environment' resulted in an error (Cannot read property '0' of undefined)

@tbkw I think this is a different problem. Can you create a new issue for this with a reproducible example? Thank you.

**Comment by andycraig** [comment] 2020-08-16 01:02
This issue was created first but there's more info in duplicate #257, so closing in favour of that.

**Closed by andycraig** 2020-08-16 01:02 UTC
Labels: bug
