### ISSUE TITLE
Dynamically update options(width)

### ISSUE THREAD

**Issue by intiben** [Ikuyadeu/vscode-R#222] opened 2020-02-07 15:55 UTC
I noticed that no matter the size of the R console in Visual Studio code the `options("width")` always returns the default `80`. Is there a way to dynamically adjust `options("width")` based on the size of the R console in VScode as it is done in Rstudio?

PS: I am hoping that this is the right place for this issue

**Comment by renkun-ken** [comment] 2020-02-07 16:32
I could not reproduce your problem.

Under both Ubuntu and macOS, the `width` option is auto-adjusted based on the size of the R console in VSCode.

I'm not sure if it is a Windows-specific issue?

**Comment by intiben** [comment] 2020-02-07 19:19
@renkun-ken I am on macOS my setup is as follows:

macOS Mojave (v10.14.6)

VScode v1.42.0
    - VSCode R v1.2.2 (the only changed option is `r.sessionWatcher": true`)
    - VSCode R LSP Client v0.1.4

R 3.6.1 
    - All packages up to date as of today
    - Using the base R console (i.e. not radian)
    - languageserver v0.3.3
    - My `.Rprofile`:
```r
source(file.path(Sys.getenv(if (.Platform$OS.type == "windows") "USERPROFILE" else "HOME"), ".vscode-R", "init.R"))
```

**Comment by renkun-ken** [comment] 2020-02-07 23:20
@intiben Yes, radian auto-adjusts the `width` option (See https://github.com/randy3k/radian#features) while R terminal does not.

If you start an R terminal, the behavior is the same.

I see https://code.visualstudio.com/api/references/vscode-api#TerminalDimensions in the API but I'm not sure how we could access the width of the terminal in VSCode? @andycraig any idea?

**Comment by andycraig** [comment] 2020-02-09 03:27
I've experienced this on Windows. It would be nice to have R update width automatically.

It seems like `TerminalDimensions` is the argument type for a few methods of a pseudoterminal: https://code.visualstudio.com/api/references/vscode-api#Pseudoterminal

I think what we want is a handler for something like `onDidChangeTerminalDimensions`. Then, we could set the `width` option each time the terminal changes size. `onDidChangeTerminalDimensions` seems to exist: https://github.com/microsoft/vscode/blob/77218d2ba07c0f29a01e30a7cb72c0e9c256b68d/src/vs/vscode.proposed.d.ts#L1080

`onDidChangeTerminalDimensions` use example: https://github.com/microsoft/vscode-extension-samples/blob/6400a0cf681876f03e1ca82b99aa46d44b4d7d78/terminal-sample/src/extension.ts#L142

But I think its status is Proposed API at the moment. It doesn't appear as a property of `vscode.window` when I try to access it.

**Comment by intiben** [comment] 2020-02-10 09:09
@renkun-ken thanks for the feedback, I am mostly working with SSH remotes (for which the VScode-R is amazing) and unfortunately I am bound to use the R terminal there. I am hoping that at some point such feature can be implemented for the R terminal, but in the meantime I can set up the `width` manually  😄

**Comment by renkun-ken** [comment] 2020-02-10 10:01
On Linux and macOS, environment variable `COLUMNS` should be useful.

Using 

```r
options(width = as.integer(Sys.getenv("COLUMNS")))
```

could set R terminal width to full terminal width.

On Windows, I'm not if there's a way to do this.

If you need automatic adjustment, you could add the following code to your `~/.Rprofile`:

```r
addTaskCallback(function(...) {
  options(width = as.integer(Sys.getenv("COLUMNS")))
  TRUE
})
```

It will update the width after each top-level user input.

**Comment by intiben** [comment] 2020-02-10 10:39
@renkun-ken this is awesome thanks a lot for the trick it works like a charm !

**Comment by renkun-ken** [comment] 2020-02-10 12:44
@intiben Glad to know it works for you. Closing now. Please feel free to reopen if you encounter further problems.

**Closed by renkun-ken** 2020-02-10 12:44 UTC
Labels: feature-request
