### ISSUE TITLE
Broken Datapreview

### ISSUE THREAD

**Issue by Ladvien** [Ikuyadeu/vscode-R#67] opened 2018-04-27 14:05 UTC
It looks like I need to re-write the Dataframe Preview.  An update to VSCode broke it.  Apparently, `workspace.rootPath` is now deprecated.  The folder path now is a property of an object inside `workspaceFolder[]`.  

_C'est la vie_.  I guess it's a good excuse to re-factor it.

On the flip side, I _think_ large dataframes will be viewable, given they've updated the open file size to 4gb.

**Comment by andycraig** [comment] 2019-02-02 10:45
Hi @Ladvien, is the issue here that `R: Data Preview` always results in the error 'This does not appear to be a dataframe'?

If so, I think that this is because `getSelection()` now returns an object (with properties `linesDownToMoveCursor` and `selectedTextArray`) whereas its use in `previewDataframe()` assumes it will return a string.

`workspace.rootPath` might be deprecated but I don't get any errors in `makeTmpDir()` where it is used.

I have a working fix for `previewDataFrame()`, so I can put together a PR if that would solve this issue (until `workspace.rootPath` is removed, anyway).

**Comment by Ladvien** [comment] 2019-02-02 12:17
Hey @andycraig,

Sadly, I've started a dev job and don't have much time to work on vscode-R.  Apologies.

But I'm really glad to hear you've got a fix.  I say PR and let's get it resolved.  And hey, thank you.

**Comment by andycraig** [comment] 2019-02-02 23:14
@Ladvien Congrats on the job! :) No worries, I should have it ready in the next couple of days.

**Comment by ohmlovesampere** [comment] 2019-03-05 01:23
The problem appears again.

**Comment by andycraig** [comment] 2019-03-09 01:19
@ohmlovesampere Oh dear, I thought this was fixed. 

It's working for me on Linux and Windows, so can you provide the following?

1. The version of vscode-R you are running. (Needs to be at least 1.0.3.)
2. The operating system you are running.
3. A short example that I can follow to reproduce the error.
4. A description of what happens when you run the example. If it produces an error message, provide that.

Thank you.

**Comment by andycraig** [comment] 2019-03-23 03:07
@ohmlovesampere Any update on this? It's hard to investigate further without a bit more information, so I'll probably close this issue again in a couple of weeks if I don't hear anything further.

**Comment by micwebnet** [comment] 2019-04-19 23:54
I'm seeing this too. Installed R extension, then Excel Viewer extension (original error wasn't telling me to, so it was a bit hard to find that extra dependency). Now I get "Dataframe failed to display" whenever I try to run Ctrl+Shift+P: R: Preview Environment. I can run individual lines with Ctrl+Enter.

This is on VS Code 1.33.1 running Windows 10 10.0.17763

![image](https://user-images.githubusercontent.com/29300459/56448416-cbde5080-62c3-11e9-9402-bcb8e18bc9bc.png)

![image](https://user-images.githubusercontent.com/29300459/56448420-da2c6c80-62c3-11e9-9c1d-4b48c16dc946.png)

**Comment by andycraig** [comment] 2019-04-20 05:17
Hi @micwebnet, thank you for posting these issues. I've reopened a separate issue for the unclear Excel Viewer dependency error message (#96). This particular issue is about `Preview Dataframe`, and it sounds like you're having trouble with `Preview Environment`. Could you create a new issue for the `Preview Environment` problem? Please include a short reproducible example, that someone can copy straight into an R file and run to produce the same error.

Thank you!

**Closed** 2019-05-01 01:48 UTC

**Comment by izk8** [comment] 2019-11-13 20:27
When I try to preview a data frame, I get the message: Visual Studio Code currently limits opening files to 20 MB. 

Using VS code 1.40.0 
Ubuntu 18.04 
R extension 1.1.8 
R tools extension 0.0.6 

@Ladvien you seem to have the same desire as me to check out the df.
